name: devcontainer
on:
    workflow_dispatch:
    push:
        branches:
        - main
        paths-ignore:
        - '.devcontainer/**'
        - '.vscode/**'
        - '**.md'
    pull_request:
        branches:
        - main
        paths-ignore:
        - '.devcontainer/**'
        - '.vscode/**'
        - '**.md'
    schedule:
        - cron: '0 0 * * 0'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            actions: write

        steps:
        -
            name: Git Checkout
            uses: actions/checkout@v4
            id: git
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
            id: qemu
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            id: buildx
        -
            name: Login to GitHub Container Registry
            id: login
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}
        -
            name: repository_owner to lower case
            id: repository_owner
            uses: Entepotenz/change-string-case-action-min-dependencies@v1
            with:
                string: ${{ github.repository_owner }}
        -
            name: repository to lower case
            id: repository
            uses: Entepotenz/change-string-case-action-min-dependencies@v1
            with:
                string: ${{ github.repository }}
        -
            name: Container Build
            uses: docker/build-push-action@v5
            id: container-build
            with:
                push: false
                cache-to: type=inline
                cache-from: type=registry,ref=ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ github.sha }}
                context: docker
                file: docker/Dockerfile
                platforms: linux/amd64,linux/arm64
                tags: "ghcr.io/${{ steps.repository.outputs.lowercase }}:latest,ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ github.sha }}"
        -
            if: ${{ github.event_name == 'push' }} && ${{ github.ref == 'refs/heads/main' }}
            name: Container Push
            uses: docker/build-push-action@v5
            id: container-push
            with:
                push: true
                cache-from: type=inline
                context: docker
                file: docker/Dockerfile
                platforms: linux/amd64,linux/arm64
                tags: "ghcr.io/${{ steps.repository.outputs.lowercase }}:latest,ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ github.sha }}"
